### PR TITLE
Added dark theme

### PR DESCRIPTION
**Pull request by guidolarosa**
Added dark theme color schemes for the documentation

### CODE REVIEW

**Comment by alcuadrado** [comment]
Hey @guidolarosa, does this version of the website saves your theme preference somehow?

**Comment by alcuadrado** [comment]
Also, you are using `npm` and committed a `package-lock.json` file. We use `yarn` instead.

**Comment by guidolarosa** [comment]
Hi @alcuadrado Patricio! 
I'll implement a way to save the user theme preference, remove the package-lock.json and push the changes again.

**Comment by guidolarosa** [comment]
Hi @alcuadrado! Changes are now ready. Please review and tell me if there's something else I need to do. Thanks

**Comment by alcuadrado** [comment]
Thanks, @guidolarosa !

**Pull request merged**
