### PR TITLE
Fix `eth_subscribe` JSON-RPC implementation for standalone nodes.

### LINKED ISSUE #588: web3 client not receiving eth_subscribe data from hardhat network
Hi, I am having a weird issue where my web3 client connecting to a local buidler-evm wasn't able to receive any event. I have a runnable example along with a control group here (https://github.com/Detoo/buidler-eth-subscribe-issue) but here's a quick summary of what I saw:

## The code snippet

```javascript
greeter.events.Greet()
        .on("data", (event) => console.log('event:', event))
        .on("error", (error) => console.log('error:', error))

await greeter.methods.greet().send()
```

## Expected Results

For sanity check, I tested the same codes with a ganache-cli evm instead and it did work:

```
$ npm run main

> buidler-eth-subscribe-issue@1.0.0 main /Users/detoo/Dropbox/playground/buidler-eth-subscribe-issue
> buidler run src/main.ts

All contracts have already been compiled, skipping compilation.
event: {
  logIndex: 0,
  transactionIndex: 0,
  transactionHash: '0x161b5b7ea58d5c634bcdef15780f5382d65d3ad257e970ef23bb827ea94fd58e',
  blockHash: '0x21da0dab9277f0a4cd7ff44db9c5ad85d2106e851f5d532b38bf5c1f88b85e34',
  blockNumber: 2,
  address: '0xbFbd287DDF9dE89ba9781c92aa21654Dac99c283',
  type: 'mined',
  id: 'log_2406fd8c',
  returnValues: Result {
    '0': '0xbFbd287DDF9dE89ba9781c92aa21654Dac99c283',
    '1': '123',
    from: '0xbFbd287DDF9dE89ba9781c92aa21654Dac99c283',
    value: '123'
  },
  event: 'Greet',
  signature: '0xc3b6fa780771bb4c77c875ed1937bd523871551d0234535b464710f4b4a10788',
  raw: {
    data: '0x000000000000000000000000000000000000000000000000000000000000007b',
    topics: [
      '0xc3b6fa780771bb4c77c875ed1937bd523871551d0234535b464710f4b4a10788',
      '0x000000000000000000000000bfbd287ddf9de89ba9781c92aa21654dac99c283'
    ]
  }
}
```

## Actual Results

However, when it run against a buidler-evm, I got nothing in response:

```
$ npm run main

> buidler-eth-subscribe-issue@1.0.0 main /Users/detoo/Dropbox/playground/buidler-eth-subscribe-issue
> buidler run src/main.ts

All contracts have already been compiled, skipping compilation.
```

The evm logs show it did receive `eth_subscribe`:

```
eth_accounts
eth_gasPrice
eth_sendTransaction
  Contract deployment: Greeter
  Contract address:    0x7c2c195cd6d34b8f845992d380aadb2730bb9c6f
  Transaction:         0xe8a7d36371b9d4dba1992c73a3690ef711dfc86bbaaeaa25b47ee403f03e3e0f
  From:                0xc783df8a850f42e7f7e57013759c285caa701eb6
  Value:               0 ETH
  Gas used:            517815 of 1000000
  Block #1:            0x09ac09a72e2330f44e9dbff16f299b7b89d6733ffed6651f650ab80ab3e23403
  
  console.log:
    Deploying a Greeter with greeting: Hello, world!

eth_getTransactionReceipt
eth_getCode
eth_subscribe
eth_gasPrice
eth_sendTransaction
  Contract call:       Greeter#greet
  Transaction:         0x92f0fadcd2d44019250beda05e1d0c39619a4f13d4ee1c0204e9c600cee685df
  From:                0xc783df8a850f42e7f7e57013759c285caa701eb6
  To:                  0x7c2c195cd6d34b8f845992d380aadb2730bb9c6f
  Value:               0 ETH
  Gas used:            24904 of 9500000
  Block #2:            0x597b49929b40507799ddaeebff602081858064119d2db4afa0cef749e051ae0f

eth_getTransactionReceipt
```

That led me to think maybe I did not setup buidler-evm properly but I not sure why. Any suggestion is very much appreciated, thanks!

### PR DESCRIPTION
**Pull request by scnale**
This modifies the Hardhat Network JSON-RPC server handler to correctly handle subscription notifications from the Hardhat Network provider.

Tests were added for:
- Websocket provider connected to a Hardhat node
  - hardhat-web3
  - hardhat-ethers
- In process Hardhat Network provider
  - hardhat-web3
  - hardhat-ethers

Fixes #588.

Note that this modifies the polling rate of the ethers provider. By default, it is set to once every 4 seconds. When a Hardhat Network provider is detected the polling rate is increased to once every 500 milliseconds.

This [reference](https://geth.ethereum.org/docs/rpc/pubsub) on `eth_subscribe` and related may be useful.
See also [EIP 1193](https://eips.ethereum.org/EIPS/eip-1193).

### CODE REVIEW

**Comment by pynchmeister** [comment]
I'm having some trouble running the tests, particularly the one found here: ```hardhat/packages/hardhat-ethers/test/index.ts```

## Steps to replicate

1. ```git clone https://github.com/nomiclabs/hardhat.git```
2. ```cd hardhat``` 
2. ```git checkout -b fix/hardhat-node-eth-subscribe```
3. ```npm i```
4. ```cd packages```
5. ```cd hardhat-ethers```
6. ```npm I```
7. ```cd test```
8. ```npm run test```


Below are the errors received:

```@nomiclabs/hardhat-ethers@2.0.1 test /Users/btccenternyc/cleanSLate/hardhat/packages/hardhat-ethers
> node ../../node_modules/mocha/bin/mocha --recursive "test/**/*.ts" --exit


Error: Cannot find module 'detect-port'
Require stack:
- /Users/btccenternyc/cleanSLate/hardhat/packages/common/ganache-provider.js
- /Users/btccenternyc/cleanSLate/hardhat/packages/common/run-with-ganache.js
- /Users/btccenternyc/cleanSLate/hardhat/node_modules/mocha/lib/esm-utils.js
- /Users/btccenternyc/cleanSLate/hardhat/node_modules/mocha/lib/mocha.js
- /Users/btccenternyc/cleanSLate/hardhat/node_modules/mocha/lib/cli/one-and-dones.js
- /Users/btccenternyc/cleanSLate/hardhat/node_modules/mocha/lib/cli/options.js
- /Users/btccenternyc/cleanSLate/hardhat/node_modules/mocha/bin/mocha
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:965:15)
    at Function.Module._load (internal/modules/cjs/loader.js:841:27)
    at Module.require (internal/modules/cjs/loader.js:1025:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/Users/btccenternyc/cleanSLate/hardhat/packages/common/ganache-provider.js:2:16)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
    at Module.require (internal/modules/cjs/loader.js:1025:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/Users/btccenternyc/cleanSLate/hardhat/packages/common/run-with-ganache.js:1:35)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
    at Module.require (internal/modules/cjs/loader.js:1025:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at requireOrImport (/Users/btccenternyc/cleanSLate/hardhat/node_modules/mocha/lib/esm-utils.js:15:12)
    at Object.exports.loadFilesAsync (/Users/btccenternyc/cleanSLate/hardhat/node_modules/mocha/lib/esm-utils.js:28:26)
    at Mocha.loadFilesAsync (/Users/btccenternyc/cleanSLate/hardhat/node_modules/mocha/lib/mocha.js:386:19)
    at singleRun (/Users/btccenternyc/cleanSLate/hardhat/node_modules/mocha/lib/cli/run-helpers.js:149:15)
    at exports.runMocha (/Users/btccenternyc/cleanSLate/hardhat/node_modules/mocha/lib/cli/run-helpers.js:186:11)
    at Object.exports.handler (/Users/btccenternyc/cleanSLate/hardhat/node_modules/mocha/lib/cli/run.js:319:11)
    at /Users/btccenternyc/cleanSLate/hardhat/node_modules/yargs/lib/command.js:241:49
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @nomiclabs/hardhat-ethers@2.0.1 test: `node ../../node_modules/mocha/bin/mocha --recursive "test/**/*.ts" --exit`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @nomiclabs/hardhat-ethers@2.0.1 test script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/btccenternyc/.npm/_logs/2021-01-21T00_25_47_166Z-debug.log
(base) btccenternyc@BTCs-iMac test % ```

Let me know if you aware of a fix or if I made a mistake anywhere, eager to use subscriptions with hardhat!

**Comment by scnale** [comment]
@pynchmeister  Hm, the Hardhat repository is setup to work with Yarn v1. It uses a root workspace to share development dependencies. I'd suggest you do this instead:

1. `git clone https://github.com/nomiclabs/hardhat.git`
2. `cd hardhat`
3. `git checkout fix/hardhat-node-eth-subscribe`
4. `yarn`
5. `cd packages/hardhat-ethers`
6. `yarn test`

**Comment by pynchmeister** [comment]
Thank you @scnale , that was a silly mistake on my part.

**Comment by pynchmeister** [comment]
Just to let you know @scnale , your steps worked up until the final yarn command. When I ran that I got the following error: 

```$ node ../../node_modules/mocha/bin/mocha --recursive "test/**/*.ts" --exit

TSError: ⨯ Unable to compile TypeScript:
src/internal/ethers-provider-wrapper.ts:2:34 - error TS2307: Cannot find module 'hardhat/types' or its corresponding type declarations.

2 import { EthereumProvider } from "hardhat/types";
                                   ~~~~~~~~~~~~~~~

    at createTSError (/Users/btccenternyc/new/hardhat/node_modules/ts-node/src/index.ts:434:12)
    at reportTSError (/Users/btccenternyc/new/hardhat/node_modules/ts-node/src/index.ts:438:19)
    at getOutput (/Users/btccenternyc/new/hardhat/node_modules/ts-node/src/index.ts:578:36)
    at Object.compile (/Users/btccenternyc/new/hardhat/node_modules/ts-node/src/index.ts:775:32)
    at Module.m._compile (/Users/btccenternyc/new/hardhat/node_modules/ts-node/src/index.ts:858:43)
    at Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Object.require.extensions.<computed> [as .ts] (/Users/btccenternyc/new/hardhat/node_modules/ts-node/src/index.ts:861:12)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
    at Module.require (internal/modules/cjs/loader.js:1025:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/Users/btccenternyc/new/hardhat/packages/hardhat-ethers/test/ethers-provider-wrapper.ts:4:1)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Module.m._compile (/Users/btccenternyc/new/hardhat/node_modules/ts-node/src/index.ts:858:23)
    at Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Object.require.extensions.<computed> [as .ts] (/Users/btccenternyc/new/hardhat/node_modules/ts-node/src/index.ts:861:12)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
    at Module.require (internal/modules/cjs/loader.js:1025:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at requireOrImport (/Users/btccenternyc/new/hardhat/node_modules/mocha/lib/esm-utils.js:15:12)
    at Object.exports.loadFilesAsync (/Users/btccenternyc/new/hardhat/node_modules/mocha/lib/esm-utils.js:28:26)
    at singleRun (/Users/btccenternyc/new/hardhat/node_modules/mocha/lib/cli/run-helpers.js:149:3)
    at exports.runMocha (/Users/btccenternyc/new/hardhat/node_modules/mocha/lib/cli/run-helpers.js:186:5)
    at Object.exports.handler (/Users/btccenternyc/new/hardhat/node_modules/mocha/lib/cli/run.js:319:5)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

This was fixed by running ```npm i``` in the packages/hardhat-ethers directory.

One more thing, you have one test failing (one that seems kind of important). I'll paste the output here:

``` 59 passing (18s)
  1 pending
  1 failing

  1) JsonRpcServer integration tests
       Using a websocket connection
         Event subscriptions
           Should receive all three events:

      AssertionError: expected [] to have a length of 3 but got 0
      + expected - actual

      -0
      +3
      
      at Context.<anonymous> (test/jsonrpc-server.ts:72:16)

```

**Comment by scnale** [comment]
Ah, I think you need to build the whole project too. The sequence of commands should look like this instead:

1. `git clone https://github.com/nomiclabs/hardhat.git`
2. `cd hardhat`
3. `git checkout fix/hardhat-node-eth-subscribe`
4. `yarn`
5. `yarn build`
6. `cd packages/hardhat-ethers`
7. `yarn test`

That failing test is due to the fact that it's using the latest released version instead of the one present in the yarn workspace. The fix is in the `hardhat-core` package.

**Comment by pynchmeister** [comment]
Thanks for the heads up @scnale , much appreciated

**Comment by sebastianst** [comment]
Is there an ETA on this one? I'm trying to replace all uses of `ganache-cli` with `hardhat node` in our projects but block header subscriptions don't seem to work.

**Comment by sebastianst** [comment]
This got closed. Does it work now? @fvictorio

**Comment by fvictorio** [comment]
@sebastianst no, we are working on it but it will be a new PR.

**Pull request closed without merging**
