### PR TITLE
chore: added hardhat-time-n-mine plugin

### PR DESCRIPTION
**Pull request by AlanVerbner**
- [x] This PR includes a **documentation change**, so its branch was created from the `website` branch, and this PR uses the `website` branch as its base branch.
- [ ] This PR includes a **bug fix**, so relevant tests have been included.
- [ ] This PR includes a **new feature**, so the change was previously discussed on an Issue or with someone from the team.
- [ ] I didn't do anything of this.

---

This PR adds a plugin to help manipulating block mining process when testing

### CODE REVIEW

**Comment by fvictorio** [comment]
Blocked by: https://github.com/atixlabs/hardhat-time-n-mine/issues/5

**Comment by AlanVerbner** [comment]
> Blocked by: [atixlabs/hardhat-time-n-mine#5](https://github.com/atixlabs/hardhat-time-n-mine/issues/5)

Thanks @fvictorio we will review it and get back to you

**Comment by AlanVerbner** [comment]
@fvictorio we fixed it on version `0.0.5`

**Comment by fvictorio** [comment]
Thanks @AlanVerbner. I can't push to your branch for some reason, but if you `cd docs && yarn lint:fix` and push, the CI should pass.

**Comment by AlanVerbner** [comment]
> Thanks @AlanVerbner. I can't push to your branch for some reason, but if you `cd docs && yarn lint:fix` and push, the CI should pass.

that should be it ... I must admit I should have read the contributing guide :facepalm:

**Pull request merged**
