### PR TITLE
Add Pull Request template

### PR DESCRIPTION
**Pull request by fvictorio**
Thank you for using Hardhat and taking the time to send a Pull Request!

- If you are sending a **documentation change**, please make sure you created your branch from the `website` branch, and that this pull request uses it as its base branch.
- If you are sending a **bug fix**, please make sure you are including relevant tests.
- If you are sending a **new feature**, please make sure you discussed it first on an issue or with someone from the team.

### CODE REVIEW

**Comment by alcuadrado** [comment]
This looks good to me.

**Comment by feuGeneA** [comment]
May I suggest that this be written _from_ the perspective of the person opening the PR, rather than being addressed _to_ them.

And may I also suggest that the template be in checklist format as an easy way of asking them to make sure they do these things.

Perhaps:

-   [ ] (If this PR includes a **documentation change**) This PR's branch was created from the `website` branch, and this PR uses the `website` branch as its it as its base branch.
-   [ ] (If this PR includes a **bug fix**) Relevant tests have been included.
-   [ ] (If this PR includes a **new feature**) The change was previously discussed on an Issue or with someone from the team.

**Comment by fvictorio** [comment]
@feuGeneA This message is meant to be deleted (at least for now), so a checklist might not make much sense. Plus, when you open a PR you get the raw markdown, and finding out how to check them is a bit annoying. I think we can start with this and add more friction later if needed.

**Comment by feuGeneA** [comment]
> @feuGeneA This message is meant to be deleted (at least for now), so a checklist might not make much sense. Plus, when you open a PR you get the raw markdown, and finding out how to check them is a bit annoying. I think we can start with this and add more friction later if needed.

I'm happy to defer to your judgement on this, but I'd like to express my disagreement and the reasons for it.

I think these items (at least, the ones that are applicable to a given PR) actually should not be deleted. I think they should be left in place as a sort of badge/indicator to confirm that the correct procedure was followed.

Since they are steps that are expected to be followed, I think it makes perfect sense for them to be checklist items.  If we are concerned that people may not know how to interact with checklist items, then we can put a comment in the raw markdown, something simple like 'To mark these items as "done," replace `[ ]` with `[x]`, or simply click the checkbox in the rendered description."

If you'd like to leave the text in there as is, may I suggest putting the entirety of the text into a comment in the raw markdown.  Leaving any text in there that *isn't* in comments feels to me like a suggestion to have the text stay in the body of the PR description.  A "template" to me should be more something that you fill in blanks in rather than something that you remove content from.  At the very least, I'd suggest a comment saying "Please delete the following text."

Thinking more, my preference would be to leave them as checklist items, but rephrase to be like, "-   [ ]  Because this PR includes a bug fix, relevant tests have been included."  And then add a markdown comment just before the checklist items saying "Please delete the checklist items that don't make sense for your PR."

Again, happy to defer to you: feel free to merge as-is; I'm not demanding changes here. :smile: But I do disagree, so I wanted to explain my reasoning.

**Comment by alcuadrado** [comment]
Wait, you can have comments in Markdown? 🤯

Then I agree that it should be within a comment, or something that the user should actually fill out and leave in the pr. No strong preference.

**Comment by fvictorio** [comment]
What do you think about adding this item?

- [ ] (If this PR includes a documentation change) This PR's branch was created from the website branch, and this PR uses the website branch as its it as its base branch.
- [ ] (If this PR includes a bug fix) Relevant tests have been included.
- [ ] (If this PR includes a new feature) The change was previously discussed on an Issue or with someone from the team.
- [x] I didn't do anything of this.

That way we have a simple example of checking an item and it works as a signal of "low effort" if someone just deletes the whole thing or doesn't edit it.

**Comment by alcuadrado** [comment]
I like it!

**Pull request merged**
