### PR TITLE
Fix 1885

### LINKED ISSUE #1885: ethereumjs-util: "This method only supports Buffer"
Seeing this error when trying to update our deps:

```
Error: This method only supports Buffer but input was: 0xac...
    at Object.exports.assertIsBuffer (/tmp/2021-09-15/19h-42m-SvG/node_modules/ethereumjs-util/src/helpers.ts:21:11)
    at Object.exports.privateToPublic (/tmp/2021-09-15/19h-42m-SvG/node_modules/ethereumjs-util/src/account.ts:275:3)
    at exports.privateToAddress (/tmp/2021-09-15/19h-42m-SvG/node_modules/ethereumjs-util/src/account.ts:285:26)
    at /tmp/2021-09-15/19h-42m-SvG/node_modules/@nomiclabs/hardhat-truffle5/src/index.ts:140:41
    at Array.map (<anonymous>)
    at describeContract (/tmp/2021-09-15/19h-42m-SvG/node_modules/@nomiclabs/hardhat-truffle5/src/index.ts:139:11)
```

https://github.com/nomiclabs/hardhat/blob/21ab17bc586e061315be45954aeb495f557972dd/packages/hardhat-truffle5/src/index.ts#L140

`acc.privateKey` is a string and `privateToAddress` expects a Buffer.

### PR DESCRIPTION
**Pull request by alcuadrado**
This PR is a continuation of #1907. 

Fixes #1885

### CODE REVIEW

**Comment by alcuadrado** [comment]
@fvictorio do you mind reviewing this tomorrow and releasing the new versions if everything looks good? According to #1885 the truffle plugins are unusable because of this.

**Review by fvictorio — APPROVED** [review]

**Comment by tina1998612** [comment]
so now if I update hardhat to latest version it should work?

**Comment by FortisFortuna** [comment]
Still had to revert to @nomiclabs/hardhat-truffle5@2.0.0 for this to work

**Comment by fvictorio** [comment]
> so now if I update hardhat to latest version it should work?

Yes

**Comment by tina1998612** [comment]
Issue resolved after running 
```bash
yarn add hardhat @nomiclabs/hardhat-truffle5
```

**Pull request merged**
