### PR TITLE
Allow contract.only in hardhat-truffle

### PR DESCRIPTION
**Pull request by frangio**
If you think this looks good I'll port to hardhat-truffle4 as well.

### CODE REVIEW

**Comment by alcuadrado** [comment]
Sorry I took so long to review this. It does look good.

**Comment by frangio** [comment]
Ported to Truffle 4 now.

**Comment by frangio** [comment]
The CI seems to have failed fo runrelated relasons.

**Comment by alcuadrado** [comment]
Sorry this took so long, @frangio. The CI is in fact failing because of a problem with Alchemy, but this looks good. Thanks!

**Pull request merged**
