### PR TITLE
added Binance Smart Chain and Fantom networks

### PR DESCRIPTION
**Pull request by purperen**
added Binance Smart Chain networks mapped them to bscscan.com api
added Fantom Opera network and mapped it to ftmscan.com api

### CODE REVIEW

**Review by fvictorio — APPROVED** [review]

**Comment by scnale** [comment]
There was a similar pull request some time ago #792. In fact, there's another one identical to #792 open right now:  #1120.

We didn't merge #792 since it seems like the API for BSC didn't work. Do we know if that has changed?
How do we test it? I personally think reusing the existing integration tests might work, but I'm not sure what their parameters should be. See the [development readme](https://github.com/nomiclabs/hardhat/blob/master/packages/hardhat-etherscan/DEVELOPING.md). In particular:
- Is using an Etherscan API key enough for BSCscan?
- What endpoint could we use for a BSC JSON-RPC node?

The same applies to the Fantom Opera network.

**Comment by fvictorio** [comment]
I tested it with the BSC testnet and it worked fine. I assume that the BSC mainnet works too. Not sure about how to test it in Fantom.

**Comment by fvictorio** [comment]
@purperen I just merged a PR that caused a conflict on this one. I think it's easy to resolve: you just need to add the browser URLs for the new networks. I'm about to release a new version of this plugin, but I can wait a little so that this PR is included in the release.

**Comment by fvictorio** [comment]
Oh, and with respect to Fantom: I wouldn't include it unless someone can point out how to test it (or at least telling us that it was tested and it worked). Is there a faucet, a testnet or something?

**Comment by purperen** [comment]
you are right problems with fantom
Error in plugin @nomiclabs/hardhat-etherscan: Failed to send contract verification request.
Endpoint URL: https://api.ftmscan.com/api

**Comment by purperen** [comment]
removed fantom network for now

**Comment by fvictorio** [comment]
Thank you @purperen!

**Comment by jin10086** [comment]
Does BSC have a recommended archive node?

**Pull request merged**
