### PR TITLE
Moonriver verify support

### PR DESCRIPTION
**Pull request by x0s0l**
- [ ] Because this PR includes a **bug fix**, relevant tests have been included.
- [ ] Because this PR includes a **new feature**, the change was previously discussed on an Issue or with someone from the team.
- [x] I didn't do anything of this.

---

### CODE REVIEW

**Comment by fvictorio** [comment]
Hi @solar-ape, thanks for submitting this. Could you please send me some testnet tokens to `0x7b3865d63d200c5016D88b36220D1D1Ae8933BBF` so I can try this?

**Comment by solar-ape** [comment]
> Hi @solar-ape, thanks for submitting this. Could you please send me some testnet tokens to `0x7b3865d63d200c5016D88b36220D1D1Ae8933BBF` so I can try this?

Heya,

There:

https://moonbase-blockscout.testnet.moonbeam.network/tx/0x8c5ed29ef69f4fec710b13e1c475c43f9a3fedea0928f4ff011a8fa5f3bc2a6d

**Comment by albertov19** [comment]
Hi @fvictorio any updates? 😄 Happy to help verifying that this works.

Thanks in advance

**Comment by wagmiwiz** [comment]
Hey @fvictorio, let us know if there anything we can do to push this along? It prevents us using HH for Moonbeam/river deployments right now.

**Comment by mario-eth** [comment]
Any update? 👀

**Comment by mario-eth** [comment]
moonriver is booming, hard to deploy and verify from remix....

**Comment by fvictorio** [comment]
Thanks for this @x0s0l.

I ended up testing this only in the Moonriver explorer. The Moonbase Alpha explorer won't work for now because there's no way to get an API key for it (yet). In other networks, using the same API key that you get for the "mainnet" works, but in this case it won't, at least for now (I don't understand the exact reasons why though).

**Comment by Enigmatic331** [comment]
Yeap... Can confirm Moonbase Alpha's API front for contract verification is still a WIP - Sorting out logistics for the API keys between user accounts for Moonbeam/Moonriver/Moonbase sites, please bear with us for now. 🙏

**Comment by villarode** [comment]
I'm trying to verify a contract on moonbase Alpha. Hardhat plugin is nort working:

Error HH303: Unrecognized task verify

**Comment by albertov19** [comment]
@villarode Moonbeam/Moonscan should be available tomorrow. You would need to create an API key there that should work with Moonbase Alpha. 

https://moonbeam.moonscan.io

**Comment by villarode** [comment]
Cheers matey

**Comment by albertov19** [comment]
@villarode it should work now!!

https://moonbeam.moonscan.io -> get an API key from there and you can use it on Moonbase Alpha

**Comment by lee-rand** [comment]
I am not able to verify a smart contract on Moonbase through hardhat plugin.
I already got my apiKey from Moonbase.
Was someone able to verify this without any issue? TX
`
...
  etherscan: { apiKey: [API_KEY]}
...
`
`npx hardhat --network moonbase verify `

**Comment by albertov19** [comment]
@lee-rand are you using version `3.0.1-rc.0`? Also, for Moonbase Alpha you need a Moonbeam API key (not Moonriver) Hopefully version `3.0.1` is launched soon

**Comment by lee-rand** [comment]
@albertov19 I am using 3.0.0. And yes. I am using a moonbeam API Key.
What's so special about 3.0.1?

Which version is working for you?

**Comment by albertov19** [comment]
@lee-rand for your use case 3.0.0 should work as it already supports Moonbase Alpha. What error are you getting? Please open an issue, tag me, and I'll help you there (better than in the PR)

**Comment by lee-rand** [comment]
@albertov19 
I am still getting `NomicLabsHardhatPluginError: Invalid API` Key when using "@nomiclabs/hardhat-etherscan": "^3.0.0"

I got my api key from `https://moonbeam.moonscan.io/`. 

`````
...
mocha: {
    timeout: 10000000,
  },
  etherscan: { apiKey: process.env.MOONBASESCAN_API_KEY_RAND },
};
`````

Any clue on whether hardhat verify plugging works properly for Moonbase? Thanks

**Comment by albertov19** [comment]
@lee-rand ahh you need to provide the API key with the following object (readme of the hardhat-etherscan package):

```
etherscan: {
    apiKey: {
        moonbaseAlpha: "YOUR_MOONBEAM_MOONSCAN_API_KEY",
    }
  }
```

Give it s shot and let me know if it worked. For the future, you should open a GitHub issue

**Comment by villarode** [comment]
Hi, would it be:

etherscan: {
    apiKey: {
        moonbaseAlpha: "YOUR_MOONBEAM_MOONSCAN_API_KEY",

        Moonriver:

"Your_moonriver_moonscan_api_key",

        Polygon:

"Your_polygon_polygonscan_api_key",

    }
  }

for multiple networks?)

**Comment by gtsui** [comment]
> @lee-rand ahh you need to provide the API key with the following object (readme of the hardhat-etherscan package):
> 
> ```
> etherscan: {
>     apiKey: {
>         moonbaseAlpha: "YOUR_MOONBEAM_MOONSCAN_API_KEY",
>     }
>   }
> ```
> 
> Give it s shot and let me know if it worked. For the future, you should open a GitHub issue

@albertov19 Can unfortunately confirm that I tried this just now as well and still running into "Invalid API Key" as well. Using hardhat-etherscan v3.0.0

**Comment by npty** [comment]
This doesn't work for me as well

**Comment by npty** [comment]
> > @lee-rand ahh you need to provide the API key with the following object (readme of the hardhat-etherscan package):
> > ```
> > etherscan: {
> >     apiKey: {
> >         moonbaseAlpha: "YOUR_MOONBEAM_MOONSCAN_API_KEY",
> >     }
> >   }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Give it s shot and let me know if it worked. For the future, you should open a GitHub issue
> 
> @albertov19 Can unfortunately confirm that I tried this just now as well and still running into "Invalid API Key" as well. Using hardhat-etherscan v3.0.0

Can confirm that it doesn't work for me as well

**Comment by albertov19** [comment]
@adradr @gtsui @npty have you tried with a more recent hardhat-etherscan version? I suggest `3.0.3`

**Pull request merged**
