### PR TITLE
Mine several blocks in a single call

### LINKED ISSUE #1112: Mine several blocks in a single call
Many users have asked about the possibility of mining multiple blocks in a single call. Right now the only way to do this is to call `evm_mine` in a loop, but this isn't very performant.

### PR DESCRIPTION
**Pull request by mul1sh**
I added a new method to allow mining of multiple blocks in a single call.

Fixes #1112

### CODE REVIEW

**Comment by mul1sh** [comment]
@bartjman well it will have to mine all those blocks, so the speed is dependent on how fast the hardhat network mines an empty block, which is usually like 1 second from my tests so far

**Comment by bartjman** [comment]
I see, that doesn't really solve our problem. What would happen is you simply jumped 100.000 block numbers?

**Comment by mul1sh** [comment]
@bartjman ahh ok let me try that🙂

**Comment by mul1sh** [comment]
Closing for now

**Comment by toshiSat** [comment]
+1

**Comment by alcuadrado** [comment]
This is close to being released, @toshiSat. See https://github.com/nomiclabs/hardhat/pull/2032

**Pull request closed without merging**
