### PR TITLE
Add Optimism mainnet and kovan networks

### PR DESCRIPTION
**Pull request by ayushm2003**
Added OPTIMISM mainnet and kovan tesnet id's and URLs
https://github.com/ethereum-optimism/optimism/issues/983

Also, @smartcontracts says hi 👋 ❤

### CODE REVIEW

**Comment by smartcontracts** [comment]
Hellooo! @ayushm2003 just as a note we're trying to refer to mainnet as "Optimistic Ethereum" and kovan as "Optimistic Kovan" just to make things a little clearer. Thanks for making this PR :-)

**Comment by fvictorio** [comment]
Thanks for the clarification!

@ayushm2003 can you update the PR to use that terminology instead?

**Review by fvictorio — APPROVED** [review]

**Comment by alcuadrado** [comment]
This is so cool 🥳🚀

**Comment by fvictorio** [comment]
We just released `@nomiclabs/hardhat-etherscan@2.1.3`, which includes this change. Thank you again @ayushm2003!

**Pull request merged**
