### PR TITLE
[feat] Add Polygon testnet support

### PR DESCRIPTION
**Pull request by tbtstl**
Quick PR to add support for polygon's testnet on `hardhat-etherscan`, using the api found [here](https://mumbai.polygonscan.com/apis#contracts).

The PR was based off of the previous work done in #1532 (thanks @BrknRobot !)

### CODE REVIEW

**Comment by fvictorio** [comment]
Hi @tbtstl, thanks for this. I would like to check that everything is working fine, but I can't get a polygonscan API key for the Mumbai testnet (there's no sign-in section). I have one for the Polygon Mainnet, but that doesn't seem to work with the Mumbai explorer. Were you able to run this? How can I get a key to try it out?

**Comment by Akkii4** [comment]
> Hi @tbtstl, thanks for this. I would like to check that everything is working fine, but I can't get a polygonscan API key for the Mumbai testnet (there's no sign-in section). I have one for the Polygon Mainnet, but that doesn't seem to work with the Mumbai explorer. Were you able to run this? How can I get a key to try it out?

I have checked in my local machine , contract verification working fine on Mumbai testnet with the Polygon Mainnet API key, as it works the same way for other blockchain's explorer too(Etherscan, BSCScan etc)  as none has seperate sign-in section for testnet, I think the branch could be merged.

**Comment by fvictorio** [comment]
> I have checked in my local machine , contract verification working fine on Mumbai testnet with the Polygon Mainnet API key, as it works the same way for other blockchain's explorer too(Etherscan, BSCScan etc) as none has seperate sign-in section for testnet, I think the branch could be merged.

Yeah, they just enabled it today. I'm going to check again now.

**Comment by kamikazechaser** [comment]
The mainnet polygonscan api key works.

**Comment by fvictorio** [comment]
Yep, works fine now. Thanks @tbtstl!

**Pull request merged**
