### PR TITLE
adds moonbeam to hardhat etherscan verify

### PR DESCRIPTION
**Pull request by albertov19**
- [x]  I didn't do anything of this.

---

This PR adds Moonbeam Network as a supported network for the `hardhat-etherscan` plugin. This was previously discussed in a PR that git merged already for Moonriver #2046 

https://moonbeam.network/
https://moonbeam.moonscan.io/

### CODE REVIEW

**Comment by albertov19** [comment]
As a proof that the PR was tested: 
image

https://moonbeam.moonscan.io/address/0x689b07e430274C4F20E47535194c8BAECd1f82b0#code

**Comment by yourbuddyconner** [comment]
Can we get this merged? In great need of this functionality to verify our contracts on Moonbeam!

**Comment by alcuadrado** [comment]
Please, take a look at point (5) of the `CONTRIBUTING.md` file of this package. Ideally, you should follow it. We may make an exception here as I don't think @albertov19 faked that screenshot.

**Comment by yourbuddyconner** [comment]
@alcuadrado anything I can do here to drive this home? Run the test suite?

**Comment by yourbuddyconner** [comment]
Dispatched a TX with some $GLMR to the requested address: https://moonbeam.moonscan.io/tx/0x6ffa5bf70f1bc3e7e95ca6d247a2ca4e06008aa5df489634c90a6b5697bc3421

**Comment by yourbuddyconner** [comment]
Dispatched a tx on Moonbeam with some $GLMR to the requested address: https://moonbeam.moonscan.io/tx/0xefa7455ef637ac748a1671b9ea67e087f9da530f1ad23c564d34724dc0daabef

**Comment by albertov19** [comment]
@alcuadrado Sorry! Did not see that last point, let me know if the tokens sent by @yourbuddyconner are enough for the tests. I've also modified the `README.md` to fix the `Multiple API keys` section.

Thanks!

**Comment by alcuadrado** [comment]
I just tested this. Thanks!

**Comment by alcuadrado** [comment]
I published this as `@nomiclabs/hardhat-etherscan@rc`. The final version will be published early next week.

**Comment by yourbuddyconner** [comment]
Thank you very much sir, appreciate you! Sorry if I was a little annoying in pushing to get this merged! 

🤟🤝

**Comment by albertov19** [comment]
@alcuadrado any news when the official `3.0.1` will be released? We are working on some documentation around this :) - Thanks in advance

**Comment by fvictorio** [comment]
Hey @albertov19, just letting you know that we released [3.0.1](https://github.com/nomiclabs/hardhat/releases/tag/%40nomiclabs%2Fhardhat-etherscan%403.0.1) yesterday :slightly_smiling_face:

**Pull request merged**
