### PR TITLE
Set the default NVM version to 16

### PR DESCRIPTION
**Pull request by wesfloyd**
NVM versions < 16 cause a memory fault issue on Macs with the M1 processor at this step: 
https://hardhat.org/tutorial/testing-contracts.html 

because of this error: 
https://stackoverflow.com/questions/65856300/wasm-code-commit-allocation-failed-process-out-of-memory

Hopefully this is helpful?

- [x] Because this PR includes a **documentation change**, its branch was created from the `website` branch, and this PR uses the `website` branch as its base branch.
- [ ] Because this PR includes a **bug fix**, relevant tests have been included.
- [ ] Because this PR includes a **new feature**, the change was previously discussed on an Issue or with someone from the team.
- [ ] I didn't do anything of this.

---

### CODE REVIEW

**Comment by fvictorio** [comment]
We usually use the lowest supported node version in the docs. I don't think changing it is a big deal, but I don't know if the fact that it doesn't work with some machines is enough reason to do it (especially because I guess M1 users know they will have compatibility issues).

@alcuadrado wdyt?

**Comment by alcuadrado** [comment]
Can you give more info on how to reproduce this, @wesfloyd? I have an M1 mac.

**Comment by wesfloyd** [comment]
Yes @alcuadrado, steps to reproduce the bug:

- (Testing on a 2021 M1 Macbook air with 8GB memory)
- Followed the [tutorial steps 2-5](https://hardhat.org/tutorial/testing-contracts.html)
- At Step 5 when I attempt to run "npx hardhat test" to see validation of the first test case
- Expected result: "Token contract ✓ Deployment should assign the total supply of tokens to the owner"
- Actual result:  I get the "Allocation failed - process out of memory" error.

Is this helpful?

**Comment by alcuadrado** [comment]
Hey @wesfloyd, I haven't had time to take a look at this yet, but thanks for the instructions. They should be enough.

**Comment by alcuadrado** [comment]
I couldn't reproduce this, but I suspect it has to do with my environment being tuned to work with node.js on an M1. I tried to start from a clean slate, but I probably failed to do it.

Should we merge this PR anyway, @fvictorio? node@16 is the active LTS version.

**Comment by fvictorio** [comment]
@alcuadrado sure

**Pull request merged**
