### PR TITLE
docs: fix typo in vscode-tests

### PR DESCRIPTION
**Pull request by paulrberg**
Pardon my pedantry.

### CODE REVIEW

**Comment by PaulRBerg** [comment]
Also, when I run `mocha --help`, I can the following documentation for the "--recursive" command-line argument:

>   --recursive          Look for tests in subdirectories                [boolean]

It seems to be a boolean, whereas the Buidler docs suggest setting its value to "test", a string. Am I misunderstanding this? Isn't the `.mocharc.json` file supposed to contain arguments for the mocha CLI?

**Comment by PaulRBerg** [comment]
And a second question: the Mocha Test Explorer README [indicates](https://marketplace.visualstudio.com/items?itemName=hbenl.vscode-mocha-test-adapter) that if we want to use the tool with TypeScript, we have to set an additional property called "mochaExplorer.require", not just "mochaExplorer.files":

```
"mochaExplorer.files": "test/**/*.ts",
"mochaExplorer.require": "ts-node/register"
```

**Comment by alcuadrado** [comment]
> Pardon my pedantry.

Actually, I love this kind of contribution @PaulRBerg ! Thanks

> It seems to be a boolean, whereas the Buidler docs suggest setting its value to "test", a string. Am I misunderstanding this? Isn't the `.mocharc.json` file supposed to contain arguments for the mocha CLI?

Will investigate this further. We've always used it that way, but it may have changed.



> But if that's the case, why not set the "files" also via `.mocharc.json` instead of the vscode settings?

Is this possible? 😱

**Comment by PaulRBerg** [comment]
> Is this possible? 😱

No idea, but it does seem to [exist](https://mochajs.org/#command-line-usage) as a command-line argument:

```sh
--require, -r        Require module                  [array] [default: (none)]
```

**Comment by alcuadrado** [comment]
Hey Paul, sorry we never got to this. Unfortunately, now it's not mergeable, so I'll close it for now. We really appreciate this kind of PRs though, so keep them coming! I promise we'll review them faster.

**Comment by paulrberg** [comment]
No worries, thanks for the update!

**Pull request closed without merging**
