### PR TITLE
Increase timeout in localhost from 25s to 40s

### LINKED ISSUE #1549: Increase timeout for localhost network
A lot of users are using the `localhost` network with a forked hardhat node. This frequently leads to timeouts for the first run. We should consider just increasing it to a larger value.

### PR DESCRIPTION
**Pull request by Amit0617**
fixes #1549 One of the issues raised there.
---

There was a commit already but that was for docs rather than actual code. So i made the required one.

### CODE REVIEW

**Comment by fvictorio** [comment]
Hey @Amit0617, what you modified is the timeout of Hardhat's test suite. The issue is about increasing the default value of the timeout property for the `localhost` network.

**Comment by Amit0617** [comment]
> Hey @Amit0617, what you modified is the timeout of Hardhat's test suite. The issue is about increasing the default value of the timeout property for the `localhost` network.

I made that following label `package:hardhat-core` in that issue.

**Comment by Amit0617** [comment]
> Hey @Amit0617, what you modified is the timeout of Hardhat's test suite. The issue is about increasing the default value of the timeout property for the `localhost` network.

Made a new commit #2161 
I believe this was the required one.

**Comment by fvictorio** [comment]
Closing in favor of #2161.

**Pull request closed without merging**
