### PR TITLE
docs: update info about @typechain/hardhat plugin

### PR DESCRIPTION
**Pull request by paulrberg**
- [x] This PR includes a **documentation change**, so its branch was created from the `website` branch, and this PR uses the `website` branch as its base branch.

---

The [@typechain/hardhat](https://github.com/ethereum-ts/TypeChain/tree/master/packages/hardhat) package supersedes [hardhat-typechain](https://duckduckgo.com/?q=hardhat-typechain&ia=web).

### CODE REVIEW

**Review by fvictorio — APPROVED** [review]

**Comment by paulrberg** [comment]
Just rebased and reapplied my edit. All automatic checks should pass now.

**Comment by fvictorio** [comment]
@paulrberg can you rebase this to branch from `website` and change the base branch of the PR? I would do it but I can't push-force to your branch :sweat_smile:

**Comment by paulrberg** [comment]
Looks like @krzkaczor handled this before we did here, via https://github.com/nomiclabs/hardhat/pull/1739.

Closing.

**Comment by krzkaczor** [comment]
Ahh sorry, I was super slow to fix linting on my PR 😓 

Thanks for working on this too!

**Comment by alcuadrado** [comment]
Oops, I merged the other one without noticing this. Thanks for this PR, @paulrberg !

**Pull request closed without merging**
