### PR TITLE
docs: list hardhat-packager in plugins list

### PR DESCRIPTION
**Pull request by paulrberg**
- [x] This PR includes a **documentation change**, so its branch was created from the `website` branch, and this PR uses the `website` branch as its base branch.

---

My first Hardhat plugin 😊

https://github.com/paulrberg/hardhat-packager

### CODE REVIEW

**Comment by fvictorio** [comment]
Hey Paul, thanks for the PR, can you move it to the end of the list?

**Comment by paulrberg** [comment]
Oh, I put it there because my plugin depends on `@typechain/hardhat`. But nevermind, I put it at the end.

Some food for thought: maybe worth separating the plugins into official plugins and community plugins, and sort both alphabetically?

**Comment by alcuadrado** [comment]
> Oh, I put it there because my plugin depends on `@typechain/hardhat`. But nevermind, I put it at the end.
> 
> Some food for thought: maybe worth separating the plugins into official plugins and community plugins, and sort both alphabetically?

We actually sort them by npm downloads, but as it's not explicitly stated it just looks like a mess. We should make it more explicit.

We will separate between official and community plugins too.

**Comment by paulrberg** [comment]
> We actually sort them by npm downloads, but as it's not explicitly stated it just looks like a mess. We should make it more explicit.

Oh, smart!

**Comment by alcuadrado** [comment]
btw, congrats on your first plugin 🥳

**Comment by paulrberg** [comment]
Thank you!! Already have an idea for another one.

**Review by fvictorio — APPROVED** [review]

**Comment by fvictorio** [comment]
Ok, fixed now. @paulrberg if you want, rebase and drop fbe935f, but it's not necessary (we don't care that much about having a clean git history).

**Review by fvictorio — APPROVED** [review]

**Comment by paulrberg** [comment]
Done!

**Comment by fvictorio** [comment]
Thanks Paul!

**Comment by paulrberg** [comment]
🚀

**Pull request merged**
