### PR TITLE
solhint: add solhint package as a peer and dev dependency

### LINKED ISSUE #799: [buidler-solhint] solhint as peerDependency
use `solhint` as a `peerDependency`, allowing users to choose between incompatible versions, ex: 2.x vs 3.x
currently `buidler-solhint` uses `"solhint": "^2.0.0"` as a dependency.

### PR DESCRIPTION
**Pull request by shalzz**
fixes #799

### CODE REVIEW

**Comment by fvictorio** [comment]
This seems to work, but it's a product question: should installing the plugin "just work" or should anyone be able to select the version of solhint they want, at the cost of an extra step?

Btw, if we do this, the readme should be updated.

@alcuadrado @fzeoli what do you think?

**Comment by alcuadrado** [comment]
Considering that npm7, which has already been released, automatically installs peer dependencies, I think it's fine.

**Review by fvictorio — APPROVED** [review]
Note for us: we'll have to use a new major when we release this.

**Comment by alcuadrado** [comment]
Hey @shalzz, we just discussed this internally and decided not to merge it. Take a look at the issue you mentioned to understand the reasoning.

Thanks anyway for submitting this PR!

**Pull request closed without merging**
