### PR TITLE
Adding Hardhat plugin for storage layout

### PR DESCRIPTION
**Pull request by 0x3bfc**
closes https://github.com/nomiclabs/hardhat/issues/1654

### CODE REVIEW

**Comment by alcuadrado** [comment]
Nice plugin!

**Comment by alcuadrado** [comment]
Oh, just noticed that this PR is based off `master`. Can you rebase it against `website`, please?

Thanks!

**Comment by fvictorio** [comment]
@0x3bfc I think you need to rebase your branch, in addition to changing the base branch of the PR.

**Comment by 0x3bfc** [comment]
> @0x3bfc I think you need to rebase your branch, in addition to changing the base branch of the PR.

Oh my bad! will update it now.

**Comment by 0x3bfc** [comment]
I'm closing this PR and reopened a new one here https://github.com/nomiclabs/hardhat/pull/1673

**Pull request closed without merging**
