### PR TITLE
Use `npx hardhat init` as an intialization workflow

### PR DESCRIPTION
**Pull request by alcuadrado**
This is an attempt at fixing #1408. Please read the comments in the diff to learn how it works.

### CODE REVIEW

**Comment by feuGeneA** [comment]
Should tihs also be added to the `--help` output?  Perhaps only if `os.type() === "Windows_NT"`?

**Comment by aftermathdigital** [comment]
Firstly, I'm as surprised as your users that `npx hardhat init` is not a thing, as it is how I initialize hardhat projects... I'm not sure where I learned it!

Secondly, unfortunately this fix doesn't fully restore the correct functionality, the user now gets the dialogue boxes, but that dialogue is not updated in response to input (pressing up/down arrows does nothing). If what I mean isn't clear, I can demo it to you to save you from using windows yourself (you philistine).

Thirdly, and I don't know if you care, `npx hardhat init > somefile.txt` now hangs, waiting for input - wheras before it would write the HH1 error to stderr and terminate.

**Comment by alcuadrado** [comment]
> I'm not sure where I learned it!

Many people use that, but in fact, `npx hardhat anything` would prompt the initialization menu if you are on a TTY (not win) and not inside a project.

> Secondly, unfortunately this fix doesn't fully restore the correct functionality, the user now gets the dialogue boxes, but that dialogue is not updated in response to input (pressing up/down arrows does nothing). If what I mean isn't clear, I can demo it to you to save you from using windows yourself (you philistine).

Oh, really? that sucks! :(

> Thirdly, and I don't know if you care, npx hardhat init > somefile.txt now hangs, waiting for input - wheras before it would write the HH1 error to stderr and terminate.

I wouldn't mind this, but the arrows not working sucks :(

**Comment by aftermathdigital** [comment]
This is acknowledged as a pain-point in the GitBash FAQ: https://github.com/git-for-windows/git/wiki/FAQ#some-native-console-programs-dont-work-when-run-from-git-bash-how-to-fix-it it has a couple of `fixes`, and I use that term lightly, but they are based around re-configuring the shell, not changing the target application

**Comment by Smyja** [comment]
> 

i get this error when i run `winpty bash "$(which npx)" hardhat init`
```

[C:\Users\USER\AppData\Local\npm-cache\_npx\ef9ef3f50c7d7dc1\node_modules\source-map\lib\util.js:208
    if (i


SyntaxError: Unexpected end of input
    at Object.compileFunction (node:vm:352:18)
    at wrapSafe (node:internal/modules/cjs/loader:1031:15)
    at Module._compile (node:internal/modules/cjs/loader:1065:27)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (C:\Users\USER\AppData\Local\npm-cache\_npx\ef9ef3f50c7d7dc1\node_modules\source-map\lib\source-map-ge
nerator.js:9:12)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)](url)
```

**Pull request closed without merging**
