### PR TITLE
Update hardhat version and missing accounts task in Getting Started doc

### PR DESCRIPTION
**Pull request by suraneti**
Seem like `accounts` task is missing.

### CODE REVIEW

**Comment by fvictorio** [comment]
Good catch, thanks! Can you please change the PR to use `website` as the base branch? (See https://github.com/nomiclabs/hardhat/blob/master/CONTRIBUTING.md#website-and-documentation-branching)

**Comment by suraneti** [comment]
@fvictorio I've changed the PR base branch to `website`.

**Comment by fvictorio** [comment]
@suraneti Sorry, I forgot to mention that you need to rebase your changes to that branch too, so that this PR only shows one commit. If you don't know how to do that let me know and I'll do it.

**Comment by suraneti** [comment]
@fvictorio I've rebased on `website` branch if it not work can you please rebase it.

**Comment by fvictorio** [comment]
Hmm, no, that didn't work. I created and merged #1206 because I can't push-force to your branch. Thanks for contributing!

**Pull request closed without merging**
