### PR TITLE
fix hex of odd length for eth_getStorageAt call when forking arbitrum

### PR DESCRIPTION
**Pull request by DZariusz**
- [x] This PR includes a **bug fix**, relevant tests have **NOT** been included - I tested locally only.

---

Fixes https://github.com/nomiclabs/hardhat/issues/1896

tested on:
- [x] Polygon - works
- [x] Arbitrum - works

### CODE REVIEW

**Comment by alcuadrado** [comment]
We got in touch with the Arbitrum team, and they mentioned that they are fixing this on their side, so I'm closing this PR. Thanks for submitting it anyway :)

**Comment by DZariusz** [comment]
> We got in touch with the Arbitrum team, and they mentioned that they are fixing this on their side, so I'm closing this PR. Thanks for submitting it anyway :)

np :) glad that will be fix that way or another :) thx!

**Comment by joshualyguessennd** [comment]
So we need to wait for Arbitrum Team to fix the issue? I've used the commit from @DZariusz and it's working fine on my computer but the issue seems to persist on other computers and in GitHub action

**Comment by HenriBrg** [comment]
Hello, is there any news about that bug from Hardhat team or Arbitrum Team ?
I encounter the same bug error when using hardhat to swap with Uniswap V3 within my contract

**Comment by joshualyguessennd** [comment]
@HenriBrg, It's really weird, I was able to run to make it run on my computer, I'm still investigating to understand why it works on my side because it's not working on another computer. 
also glad to meet  a "piscineux" :)

**Pull request closed without merging**
